version: '3'
services:
  myapp-main:
    image: sdat-qap2:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://springboot-pumpkinsapi.cotkikmzpd7m.us-east-1.rds.amazonaws.com/springbootapi?enabledTLSProtocols=TLSv1.2
      - spring.datasource.password=Pumpkin43
      - spring.datasource.username=admin
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver